// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "credit-layer/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// AppRepository is an autogenerated mock type for the AppRepository type
type AppRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, name, apiKey
func (_m *AppRepository) Create(ctx context.Context, name string, apiKey string) (*domain.App, error) {
	ret := _m.Called(ctx, name, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.App
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.App, error)); ok {
		return rf(ctx, name, apiKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.App); ok {
		r0 = rf(ctx, name, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.App)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, apiKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExistsByName provides a mock function with given fields: ctx, name
func (_m *AppRepository) ExistsByName(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByName")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByAPIKey provides a mock function with given fields: ctx, apiKey
func (_m *AppRepository) GetByAPIKey(ctx context.Context, apiKey string) (*domain.App, error) {
	ret := _m.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for GetByAPIKey")
	}

	var r0 *domain.App
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.App, error)); ok {
		return rf(ctx, apiKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.App); ok {
		r0 = rf(ctx, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.App)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAppRepository creates a new instance of AppRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppRepository {
	mock := &AppRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
