// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "credit-layer/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// CreditLedgerRepository is an autogenerated mock type for the CreditLedgerRepository type
type CreditLedgerRepository struct {
	mock.Mock
}

// AddCredits provides a mock function with given fields: ctx, appID, userID, amount, description, idempotencyKey
func (_m *CreditLedgerRepository) AddCredits(ctx context.Context, appID string, userID string, amount int64, description *string, idempotencyKey *string) (*domain.CreditLedger, error) {
	ret := _m.Called(ctx, appID, userID, amount, description, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for AddCredits")
	}

	var r0 *domain.CreditLedger
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, *string, *string) (*domain.CreditLedger, error)); ok {
		return rf(ctx, appID, userID, amount, description, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, *string, *string) *domain.CreditLedger); ok {
		r0 = rf(ctx, appID, userID, amount, description, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CreditLedger)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64, *string, *string) error); ok {
		r1 = rf(ctx, appID, userID, amount, description, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeductCredits provides a mock function with given fields: ctx, appID, userID, amount, description, idempotencyKey
func (_m *CreditLedgerRepository) DeductCredits(ctx context.Context, appID string, userID string, amount int64, description *string, idempotencyKey *string) (*domain.CreditLedger, error) {
	ret := _m.Called(ctx, appID, userID, amount, description, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for DeductCredits")
	}

	var r0 *domain.CreditLedger
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, *string, *string) (*domain.CreditLedger, error)); ok {
		return rf(ctx, appID, userID, amount, description, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, *string, *string) *domain.CreditLedger); ok {
		r0 = rf(ctx, appID, userID, amount, description, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CreditLedger)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64, *string, *string) error); ok {
		r1 = rf(ctx, appID, userID, amount, description, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBalance provides a mock function with given fields: ctx, appID, userID
func (_m *CreditLedgerRepository) GetBalance(ctx context.Context, appID string, userID string) (int64, error) {
	ret := _m.Called(ctx, appID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, appID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, appID, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, appID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCreditLedgerRepository creates a new instance of CreditLedgerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreditLedgerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreditLedgerRepository {
	mock := &CreditLedgerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
