// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credits.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addCredits = `-- name: AddCredits :one
INSERT INTO credit_ledger (app_id, user_id, amount, description, idempotency_key)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (idempotency_key) DO UPDATE
SET idempotency_key = EXCLUDED.idempotency_key
RETURNING id, app_id, user_id, amount, description, idempotency_key, created_at
`

type AddCreditsParams struct {
	AppID          uuid.UUID      `json:"app_id"`
	UserID         string         `json:"user_id"`
	Amount         int64          `json:"amount"`
	Description    sql.NullString `json:"description"`
	IdempotencyKey sql.NullString `json:"idempotency_key"`
}

func (q *Queries) AddCredits(ctx context.Context, arg AddCreditsParams) (CreditLedger, error) {
	row := q.db.QueryRowContext(ctx, addCredits,
		arg.AppID,
		arg.UserID,
		arg.Amount,
		arg.Description,
		arg.IdempotencyKey,
	)
	var i CreditLedger
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.UserID,
		&i.Amount,
		&i.Description,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const createApp = `-- name: CreateApp :one
INSERT INTO apps (name, api_key)
VALUES ($1, $2)
RETURNING id, name, api_key, created_at
`

type CreateAppParams struct {
	Name   string `json:"name"`
	ApiKey string `json:"api_key"`
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRowContext(ctx, createApp, arg.Name, arg.ApiKey)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
	)
	return i, err
}

const deductCredits = `-- name: DeductCredits :one
INSERT INTO credit_ledger (app_id, user_id, amount, description, idempotency_key)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (idempotency_key) DO UPDATE
SET idempotency_key = EXCLUDED.idempotency_key
RETURNING id, app_id, user_id, amount, description, idempotency_key, created_at
`

type DeductCreditsParams struct {
	AppID          uuid.UUID      `json:"app_id"`
	UserID         string         `json:"user_id"`
	Amount         int64          `json:"amount"`
	Description    sql.NullString `json:"description"`
	IdempotencyKey sql.NullString `json:"idempotency_key"`
}

func (q *Queries) DeductCredits(ctx context.Context, arg DeductCreditsParams) (CreditLedger, error) {
	row := q.db.QueryRowContext(ctx, deductCredits,
		arg.AppID,
		arg.UserID,
		arg.Amount,
		arg.Description,
		arg.IdempotencyKey,
	)
	var i CreditLedger
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.UserID,
		&i.Amount,
		&i.Description,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const existsAppByName = `-- name: ExistsAppByName :one
SELECT EXISTS (
    SELECT 1 FROM apps WHERE name = $1
)
`

func (q *Queries) ExistsAppByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsAppByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAppByAPIKey = `-- name: GetAppByAPIKey :one
SELECT id, name, api_key, created_at FROM apps
WHERE api_key = $1
`

func (q *Queries) GetAppByAPIKey(ctx context.Context, apiKey string) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByAPIKey, apiKey)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
	)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT COALESCE(SUM(amount), 0)::bigint AS balance
FROM credit_ledger
WHERE app_id = $1 AND user_id = $2
`

type GetBalanceParams struct {
	AppID  uuid.UUID `json:"app_id"`
	UserID string    `json:"user_id"`
}

func (q *Queries) GetBalance(ctx context.Context, arg GetBalanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBalance, arg.AppID, arg.UserID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}
