// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	ApiKey    string    `json:"api_key"`
	CreatedAt time.Time `json:"created_at"`
}

type CreditLedger struct {
	ID             uuid.UUID   `json:"id"`
	AppID          uuid.UUID   `json:"app_id"`
	UserID         string      `json:"user_id"`
	Amount         int64       `json:"amount"`
	Description    pgtype.Text `json:"description"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	CreatedAt      time.Time   `json:"created_at"`
}
